### ISSUE TITLE
Azure serverless SQL db on pause breaks CI Deploy task

### ISSUE THREAD

**Issue by MikkelHansenAbtion** [abtion/muffi.net#3]
The database needs to restart in order to apply migrations in CI flow, but as it pauses after a 1 hour inactivity period, no connection is made in the CI flow.
This may be fixed by not allowing pauses in serverless mode or switching from serverless db.
or
Finding a way in CI to wake up the DB from paused state and wait for it to be ready

**Comment by KlausEnevoldsen-Abtion** [comment]
Problem solved in https://github.com/abtion/muffi.net/commit/0c5ae2f0b19011bf2881cb039efdc095f5258545
